### ISSUE TITLE
Erro ao fazer login

### ISSUE THREAD

**Issue by davidhsv** [arthurnobrega/bb-api#2]
Primeiramente, ótimo trabalho, código está lindo demais e me ajuda bastante numa integração financeira pessoal.

Ao erro:

Ao fazer login, está dando erro "Opa! Encontramos um erro, mas é fácil resolver. Favor fechar o aplicativo e abrir novamente.

Código: S400".

Alguma orientação em como debugar esse erro? Como vocês fazem a engenharia reversa no aplicativo do bb?

**Comment by arthurnobrega** [comment]
Olá @davidhsv! Valeu pelo elogio!

Vou dar uma olhada nisso para ver o que pode ser.

Algumas partes foram inspiradas na lib em python https://github.com/kamushadenes/bankscraper. Outras partes foram sendo descobertas na tentativa e erro fazendo chamadas pelo Postman.
